name: CI

# Enable Buildkit and set up environment variables for optimization
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

  push:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1  # For linter checks

  unittest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    env:
      DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/postgres'

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Create Virtual Environment & Install Dependencies
        run: |
          python -m pip install uv                                   # Ensure uv is installed
          uv venv --activate                                         # Create and activate a virtual environment
          uv pip install -r requirements/local.txt                  # Install dependencies in the virtual environment

      - name: Check DB Migrations
        env:
          DJANGO_SETTINGS_MODULE: config.settings.test
        run: python manage.py makemigrations --check

      - name: Apply DB Migrations
        env:
          DJANGO_SETTINGS_MODULE: config.settings.test
        run: python manage.py migrate

      - name: Run Unit Tests
        env:
          DJANGO_SETTINGS_MODULE: config.settings.test
        run: python manage.py test
